<?php
namespace WPPT\Admin;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Admin_Settings {

	/**
	 * Register the top-level menu.
	 */
	public function register_menu(): void {
		add_menu_page(
			__( 'Performance Toolkit', 'wp-performance-toolkit' ),
			__( 'Performance', 'wp-performance-toolkit' ),
			'manage_options',
			'wp-performance-toolkit',
			[ $this, 'render_dashboard' ],
			'dashicons-performance',
			2
		);
	}

	/**
	 * Enqueue assets only on the plugin dashboard and pass telemetry data.
	 */
	public function enqueue_assets( $hook ): void {
		if ( 'toplevel_page_wp-performance-toolkit' !== $hook ) {
			return;
		}

		// Enqueue pure CSS and Vanilla JS.
		wp_enqueue_style( 'wppt-admin-css', WPPT_URL . 'admin/assets/css/admin.css', [], WPPT_VERSION );
		wp_enqueue_script( 'wppt-admin-js', WPPT_URL . 'admin/assets/js/admin.js', [], WPPT_VERSION, true );

		// Retrieve data from Module 1 (Performance Analyzer).
		$snapshot = get_transient( 'wppt_latest_performance_snapshot' );
		$history  = get_option( 'wppt_performance_history', [] );

		// Calculate a basic performance score (0-100) based on load time.
		// Logic: 100 is perfect, -1 point for every 50ms of load time.
		$score = 0;
		if ( $snapshot && isset( $snapshot['load_time'] ) ) {
			$score = max( 0, 100 - floor( $snapshot['load_time'] / 50 ) );
		}

		// Prepare data for the JS dashboard.
		$stats_data = [
			'score'     => $score,
			'ttfb'      => $snapshot['ttfb'] ?? 0,
			'load_time' => $snapshot['load_time'] ?? 0,
			'requests'  => $snapshot['requests'] ?? 0,
			'dom_count' => $snapshot['dom_count'] ?? 0,
			'js_kb'     => $snapshot['js_kb'] ?? 0,
			'css_kb'    => $snapshot['css_kb'] ?? 0,
			'img_kb'    => $snapshot['img_kb'] ?? 0,
			'history'   => $history,
			'nonce'     => wp_create_nonce( 'wppt_admin_nonce' ),
			'i18n'      => [
				'no_data' => __( 'No data collected yet. Visit your homepage to run analysis.', 'wp-performance-toolkit' )
			]
		];

		wp_localize_script( 'wppt-admin-js', 'wpptStats', $stats_data );
	}

	/**
	 * Render the modern SaaS-style dashboard skeleton.
	 */
	public function render_dashboard(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}
		?>
		<div class="wrap wppt-dashboard">
			<header class="wppt-header">
				<h1><?php echo esc_html__( 'WordPress Performance Toolkit', 'wp-performance-toolkit' ); ?></h1>
				<p class="description"><?php echo esc_html__( 'Real-time performance diagnostics and optimization hub.', 'wp-performance-toolkit' ); ?></p>
			</header>

			<!-- Performance Score Section -->
			<section class="wppt-score-card">
				<div class="wppt-score-circle">
					<!-- SVG Gauge generated by JS -->
					<span class="wppt-score-value">--</span>
				</div>
				<div class="wppt-score-meta">
					<div class="wppt-status-badge"><?php esc_html_e( 'System Status: Active', 'wp-performance-toolkit' ); ?></div>
					<p id="wppt-last-run-msg" style="margin-top: 10px; color: var(--wppt-text-muted); font-size: 13px;"></p>
				</div>
			</section>

			<!-- Metrics Grid -->
			<div class="wppt-grid">
				<article class="wppt-card">
					<h3><?php esc_html_e( 'Requests', 'wp-performance-toolkit' ); ?></h3>
					<div class="wppt-metric" id="metric-requests">--</div>
				</article>

				<article class="wppt-card">
					<h3><?php esc_html_e( 'Load Time', 'wp-performance-toolkit' ); ?></h3>
					<div class="wppt-metric" id="metric-load-time">--ms</div>
				</article>

				<article class="wppt-card">
					<h3><?php esc_html_e( 'TTFB', 'wp-performance-toolkit' ); ?></h3>
					<div class="wppt-metric" id="metric-ttfb">--ms</div>
				</article>

				<article class="wppt-card">
					<h3><?php esc_html_e( 'DOM Elements', 'wp-performance-toolkit' ); ?></h3>
					<div class="wppt-metric" id="metric-dom">--</div>
				</article>
			</div>

			<!-- Main Chart & Analysis Container -->
			<main class="wppt-main-content">
				<div class="wppt-chart-container">
					<div class="wppt-chart-header">
						<h2><?php esc_html_e( 'Load Time History', 'wp-performance-toolkit' ); ?></h2>
					</div>
					<div class="wppt-chart-placeholder" id="wppt-history-chart">
						<!-- SVG Sparkline generated by JS -->
					</div>
				</div>

				<aside class="wppt-sidebar">
					<div class="wppt-card">
						<h3><?php esc_html_e( 'Database Optimization', 'wp-performance-toolkit' ); ?></h3>
						<p style="font-size: 13px; margin-bottom: 15px;"><?php esc_html_e( 'Clean up revisions and transients to improve DB response time.', 'wp-performance-toolkit' ); ?></p>
						<button id="wppt-optimize-db" class="button button-primary" style="width: 100%; justify-content: center; display: flex;">
							<?php esc_html_e( 'Optimize Now', 'wp-performance-toolkit' ); ?>
						</button>
					</div>
				</aside>
			</main>
		</div>
		<?php
	}
}